/*
SQLyog Ultimate v11.11 (64 bit)
MySQL - 5.1.73-community : Database - etracs25_panabo
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`etracs25_panabo` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `etracs25_panabo`;

/*Table structure for table `billitem_txntype` */

DROP TABLE IF EXISTS `billitem_txntype`;

CREATE TABLE `billitem_txntype` (
  `objid` varchar(50) NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `category` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`objid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `billitem_txntype` */

insert  into `billitem_txntype`(`objid`,`title`,`category`) values ('ACCESSORY_FEE','ACCESSORY FEE','OBO'),('BLDG_ACCESSORY','BLDG ACCESSORY FEE','OBO'),('BUILDING_FEE','BUILDING FEE','OBO'),('CUSA','CUSA','MARKET'),('ELECTRICAL','ELECTRICAL FEE','OBO'),('ELECTRICAL_INSPECTION','ELECTRICAL INSPECTION FEE','OBO'),('ELECTRICITY','ELECTRICITY','MARKET'),('EXT','EXTENSION FEE','MARKET'),('FEE','FEE','GENERAL'),('INTEREST','INTEREST','GENERAL'),('MARKETRENTAL','MARKET RENTAL','MARKET'),('MECHANICAL','MECHANICAL FEE','OBO'),('MECHANICAL_INSPECTION','MECHANICAL INSPECTION FEE','OBO'),('OCCUPANCY_FEE','OCCUPANCY FEE','OBO'),('PLUMBING','PLUMBING FEE','OBO'),('SURCHARGE','SURCHARGE','GENERAL'),('WATER','WATER','MARKET');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
